/*
 * Odessa State environmental University
 * Copyright (C) 2013
 */

package ua.edu.odeku.ceem.mapRadar.tools.radarManager.panel;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.util.ResourceBundle;

/**
 * User: Aleo Bakalov
 * Date: 13.12.13
 * Time: 13:44
 */
public class RadarEditorForm {
    private JPanel panel1;
    private JSpinner transmotterPowerSpinner;
    private JSpinner AntenaGainSpinner;
    private JSpinner EffectiveAreaSpinner;
    private JSpinner scatteringCrossSectionSpinner;
    private JSpinner minimumReceiverSensitivitySpinner;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        this.$$$loadLabelText$$$(label1, ResourceBundle.getBundle("strings").getString("lavel_radarManager_editor_transmitterPower"));
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(3, 3, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        this.$$$loadLabelText$$$(label2, ResourceBundle.getBundle("strings").getString("label_radarManager_antenaGain"));
        panel1.add(label2, cc.xy(3, 5, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        transmotterPowerSpinner = new JSpinner();
        panel1.add(transmotterPowerSpinner, cc.xy(5, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        AntenaGainSpinner = new JSpinner();
        panel1.add(AntenaGainSpinner, cc.xy(5, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        this.$$$loadLabelText$$$(label3, ResourceBundle.getBundle("strings").getString("label_radarManager_effectiveArea"));
        panel1.add(label3, cc.xy(3, 7, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        EffectiveAreaSpinner = new JSpinner();
        panel1.add(EffectiveAreaSpinner, cc.xy(5, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label4 = new JLabel();
        this.$$$loadLabelText$$$(label4, ResourceBundle.getBundle("strings").getString("label_radarManager_editor"));
        panel1.add(label4, cc.xy(3, 9));
        scatteringCrossSectionSpinner = new JSpinner();
        panel1.add(scatteringCrossSectionSpinner, cc.xy(5, 9, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label5 = new JLabel();
        this.$$$loadLabelText$$$(label5, ResourceBundle.getBundle("strings").getString("label_radarManager_editor_minimumReceiverSensitivity"));
        panel1.add(label5, cc.xy(3, 11));
        minimumReceiverSensitivitySpinner = new JSpinner();
        panel1.add(minimumReceiverSensitivitySpinner, cc.xy(5, 11, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
