/*
 * Odessa State environmental University
 * Copyright (C) 2014
 */

package ua.edu.odeku.ceem.mapRadar.tools.radar.panel;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import ua.edu.odeku.ceem.mapRadar.db.model.GeoNamesWithNameAndCoordinates;
import ua.edu.odeku.ceem.mapRadar.tools.radar.airspace.entry.AirspaceEntryMessage;
import ua.edu.odeku.ceem.mapRadar.tools.radar.panel.handlerForm.HandlerRadarEditorFrom;
import ua.edu.odeku.ceem.mapRadar.utils.gui.forms.LocationForm;

import javax.swing.*;
import java.util.ResourceBundle;

/**
 * User: Aleo Bakalov
 * Date: 13.12.13
 * Time: 13:44
 */
public class RadarEditorForm {
    private JPanel panel1;
    public JTextField nameAirspaceTextField;
    public LocationForm locationForm;
    public RadarParameterForm radarParameterForm;

    public final HandlerRadarEditorFrom handler;
    public final JFrame parent;

    public RadarEditorForm(JFrame parent, AirspaceEntryMessage airspaceEntryMessage) {
        this.parent = parent;
        /*
        GUI
         */
        $$$setupUI$$$();

        /*
        Создаем обработчик что бы можно было инициализировать некоторые элименты
         */
        handler = new HandlerRadarEditorFrom(this, airspaceEntryMessage);
    }

    private void createUIComponents() {
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        locationForm = new LocationForm();
        CellConstraints cc = new CellConstraints();
        panel1.add(locationForm.$$$getRootComponent$$$(), cc.xy(1, 3));
        radarParameterForm = new RadarParameterForm();
        panel1.add(radarParameterForm.$$$getRootComponent$$$(), cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
